[package]
name = "testcontract"
version = "0.0.0"

[dependencies]
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "d9cfa0077ebf55c4a95228eff5ebbda1c9c36e1c" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "1.0.4" }

[addresses]
std =  "0x1"
